server:
  applicationConnectors:
  - type: http
    port: 5001
  adminConnectors:
  - type: http
    port: 6001
  requestLog:
    appenders: []

logging:
  level: DEBUG
  loggers:
    de.hsma.ppr.blockchain: TRACE
    javax.management: INFO
    io.dropwizard: INFO
    org.eclipse.jetty: INFO
    org.glassfish.jersey: INFO
  appenders:
  - type: console

bootnodes:
  self: ws://localhost:5001 