server:
  applicationConnectors:
  - type: http
    port: 5101
  adminConnectors:
  - type: http
    port: 6101
  requestLog:
    appenders: []

logging:
  level: ERROR
  loggers:
    de.hsma.ppr.blockchain.node.mining.Miner: INFO
    # de.hsma.ppr.blockchain: INFO
    # javax.management: INFO
    io.dropwizard: INFO
    # org.eclipse.jetty: INFO
    # org.glassfish.jersey: INFO
  appenders:
  - type: console

bootnodes:
  urls: []

peers: 
  broadcast: false
  urls: []

# miner:
#   executor:
#     threads: 2