###
# GET :5001/blocks
###
GET http://localhost:5101/blocks HTTP/1.1
###
# PUT :5001/data
###
PUT http://localhost:5101/data HTTP/1.1
content-type: application/json

{
   "key": "x"
}
###
# GET :5001/data
###
GET http://localhost:5101/data HTTP/1.1
###
# :5002/blocks
###
GET http://localhost:5102/blocks HTTP/1.1
###
# :5003/blocks
###
GET http://localhost:5103/blocks HTTP/1.1
###
# :5003/mine
###
POST http://localhost:5103/mine HTTP/1.1